/**
 * KrishiLink - Database Seeding Script
 * Realistic Bangladeshi Agricultural Data for Jamalpur Sadar, Melandaha, Islampur, Bogura, and Dhaka
 */

export const SEED_FARMERS = [
  {
    id: "farmer-1",
    name: "Alhaj Mokbul Hossain",
    phone: "01711223344",
    email: "mokbul.jamalpur@krishilink.com",
    village: "Kendua, Jamalpur Sadar",
    upazila: "Jamalpur Sadar",
    district: "Jamalpur",
    division: "Mymensingh",
    lat: 24.9250,
    lng: 89.9450,
    rating: 4.95,
    ratingsCount: 84,
    salesTaka: 428000,
    landAcres: 4.5,
    bio: "২৫ বছর ধরে বিষমুক্ত উচ্চফলনশীল আমন ও বোরো ধান চাষ করছি।",
    nidNumber: "1972391209384912",
    isNidVerified: true,
    organicCertified: true,
  },
  {
    id: "farmer-2",
    name: "Abdul Karim Mia",
    phone: "01722334455",
    email: "karim.melandaha@krishilink.com",
    village: "Hazrabari, Melandaha",
    upazila: "Melandaha",
    district: "Jamalpur",
    division: "Mymensingh",
    lat: 24.9650,
    lng: 89.8450,
    rating: 4.88,
    ratingsCount: 62,
    salesTaka: 310500,
    landAcres: 3.2,
    bio: "মেলাঙ্গার বিখ্যাত লাল মরিচ ও দেশি বেগুনের বিশেষ কৃষক।",
    nidNumber: "1981293847562019",
    isNidVerified: true,
    organicCertified: true,
  },
  {
    id: "farmer-3",
    name: "Rokeya Begum",
    phone: "01733445566",
    email: "rokeya.islampur@krishilink.com",
    village: "Gaidar Char, Islampur",
    upazila: "Islampur",
    district: "Jamalpur",
    division: "Mymensingh",
    lat: 25.0830,
    lng: 89.7820,
    rating: 4.92,
    ratingsCount: 45,
    salesTaka: 245000,
    landAcres: 2.8,
    bio: "যমুনার পলিমাটিতে উৎপাদিত মিষ্টিকুমড়া ও পটল চাষে জাতীয় পুরস্কারপ্রাপ্ত।",
    nidNumber: "1985394857201928",
    isNidVerified: true,
    organicCertified: true,
  },
  {
    id: "farmer-4",
    name: "Nazrul Islam",
    phone: "01744556677",
    email: "nazrul.sarishabari@krishilink.com",
    village: "Pogaldigha, Sarishabari",
    upazila: "Sarishabari",
    district: "Jamalpur",
    division: "Mymensingh",
    lat: 24.7450,
    lng: 89.8250,
    rating: 4.75,
    ratingsCount: 38,
    salesTaka: 189000,
    landAcres: 3.0,
    bio: "সরিষা ও মসুর ডাল সরাসরি ফার্মগেট মূল্যে সারা দেশে সরবরাহ করি।",
    nidNumber: "1978294857102938",
    isNidVerified: true,
    organicCertified: false,
  },
  {
    id: "farmer-5",
    name: "Shahidul Alam",
    phone: "01755667788",
    email: "shahidul.sadar@krishilink.com",
    village: "Sharifpur, Jamalpur Sadar",
    upazila: "Jamalpur Sadar",
    district: "Jamalpur",
    division: "Mymensingh",
    lat: 24.9120,
    lng: 89.9650,
    rating: 4.90,
    ratingsCount: 71,
    salesTaka: 512000,
    landAcres: 5.0,
    bio: "আধুনিক কোল্ড স্টোরেজ সমর্থিত ডায়মন্ড আলু ও কাঁচামরিচের পাইকারি উৎপাদক।",
    nidNumber: "1975294857201948",
    isNidVerified: true,
    organicCertified: true,
  },
  {
    id: "farmer-6",
    name: "Mofizur Rahman",
    phone: "01766778899",
    email: "mofizur.madarganj@krishilink.com",
    village: "Gunaritala, Madarganj",
    upazila: "Madarganj",
    district: "Jamalpur",
    division: "Mymensingh",
    lat: 24.9000,
    lng: 89.7500,
    rating: 4.82,
    ratingsCount: 29,
    salesTaka: 154000,
    landAcres: 2.1,
    bio: "দেশি জাতের গোল বেগুন এবং শসা সরাসরি চাষি ভাইদের কাছ থেকে।",
    nidNumber: "1986293847102947",
    isNidVerified: true,
    organicCertified: false,
  },
  {
    id: "farmer-7",
    name: "Zahirul Haque",
    phone: "01777889900",
    email: "zahirul.bakshiganj@krishilink.com",
    village: "Nilakhia, Bakshiganj",
    upazila: "Bakshiganj",
    district: "Jamalpur",
    division: "Mymensingh",
    lat: 25.2200,
    lng: 89.8700,
    rating: 4.89,
    ratingsCount: 53,
    salesTaka: 367000,
    landAcres: 4.2,
    bio: "পাহাড়ের পাদদেশে সুস্বাদু আদা, হলুদ এবং কাটারিভোগ চাল চাষ করি।",
    nidNumber: "1980293847102938",
    isNidVerified: true,
    organicCertified: true,
  },
  {
    id: "farmer-8",
    name: "Anisur Rahman",
    phone: "01788990011",
    email: "anisur.dewanganj@krishilink.com",
    village: "Chukaibari, Dewanganj",
    upazila: "Dewanganj",
    district: "Jamalpur",
    division: "Mymensingh",
    lat: 25.1400,
    lng: 89.7700,
    rating: 4.79,
    ratingsCount: 34,
    salesTaka: 215000,
    landAcres: 3.5,
    bio: "যমুনার টাটকা রুই, কাতল মাছ এবং মিষ্টি ভুট্টা চাষ।",
    nidNumber: "1984293847501928",
    isNidVerified: true,
    organicCertified: true,
  },
  {
    id: "farmer-9",
    name: "Sirajul Islam Master",
    phone: "01799001122",
    email: "sirajul.sadar@krishilink.com",
    village: "Titapalla, Jamalpur Sadar",
    upazila: "Jamalpur Sadar",
    district: "Jamalpur",
    division: "Mymensingh",
    lat: 24.8900,
    lng: 89.9200,
    rating: 4.96,
    ratingsCount: 92,
    salesTaka: 620000,
    landAcres: 6.0,
    bio: "মডেল এগ্রো ফার্ম - মালচিং পদ্ধতিতে ক্যাপসিকাম, ব্রকলি ও টমেটো।",
    nidNumber: "1969293847102938",
    isNidVerified: true,
    organicCertified: true,
  },
  {
    id: "farmer-10",
    name: "Faruk Ahmed",
    phone: "01700112233",
    email: "faruk.melandaha@krishilink.com",
    village: "Mahmoodpur, Melandaha",
    upazila: "Melandaha",
    district: "Jamalpur",
    division: "Mymensingh",
    lat: 24.9800,
    lng: 89.8100,
    rating: 4.85,
    ratingsCount: 41,
    salesTaka: 289000,
    landAcres: 2.7,
    bio: "রপ্তানিযোগ্য মানসম্মত পেঁয়াজ ও দেশি রসুন চাষি।",
    nidNumber: "1988293847102947",
    isNidVerified: true,
    organicCertified: false,
  }
];

export const SEED_COLD_STORAGES = [
  {
    id: "cs-1",
    name: "Jamalpur Modern Cold Chain Ltd",
    upazila: "Jamalpur Sadar",
    district: "Jamalpur",
    address: "Bypass Road, Beltia, Jamalpur Sadar",
    lat: 24.9180,
    lng: 89.9510,
    totalCapTons: 6000,
    availCapTons: 1850,
    tempC: 2.5,
    humidity: 88,
    ratePerBagMonth: 105,
    contactPhone: "01712-998877",
    managerName: "Engr. Tanvir Ahmed",
  },
  {
    id: "cs-2",
    name: "Melandaha Agro Himagar",
    upazila: "Melandaha",
    district: "Jamalpur",
    address: "Hazrabari Road, Melandaha",
    lat: 24.9620,
    lng: 89.8420,
    totalCapTons: 4500,
    availCapTons: 920,
    tempC: 3.0,
    humidity: 85,
    ratePerBagMonth: 110,
    contactPhone: "01715-443322",
    managerName: "Kamal Uddin",
  },
  {
    id: "cs-3",
    name: "Brahmaputra Cold Storage & Logistics",
    upazila: "Jamalpur Sadar",
    district: "Jamalpur",
    address: "Nandina Bazar, Jamalpur",
    lat: 24.8720,
    lng: 89.9920,
    totalCapTons: 5000,
    availCapTons: 2100,
    tempC: 2.0,
    humidity: 90,
    ratePerBagMonth: 100,
    contactPhone: "01720-667788",
    managerName: "Rafiqul Islam",
  },
  {
    id: "cs-4",
    name: "Islampur Char Agri Preserve",
    upazila: "Islampur",
    district: "Jamalpur",
    address: "Station Road, Islampur",
    lat: 25.0780,
    lng: 89.7890,
    totalCapTons: 3500,
    availCapTons: 640,
    tempC: 2.8,
    humidity: 87,
    ratePerBagMonth: 115,
    contactPhone: "01733-112233",
    managerName: "Saiful Islam",
  },
  {
    id: "cs-5",
    name: "Sarishabari Green Cold Network",
    upazila: "Sarishabari",
    district: "Jamalpur",
    address: "Arambagh, Sarishabari",
    lat: 24.7480,
    lng: 89.8210,
    totalCapTons: 4000,
    availCapTons: 1400,
    tempC: 2.2,
    humidity: 86,
    ratePerBagMonth: 108,
    contactPhone: "01744-889900",
    managerName: "Mizanur Rahman",
  }
];

export const SEED_PRODUCTS = [
  {
    id: "prod-1",
    farmerId: "farmer-1",
    name: "Jamalpur Boro Dhan (BRRI-28 Premium)",
    banglaName: "জামালপুর বোরো ধান (ব্রি-২৮ প্রিমিয়াম)",
    category: "DHAN",
    variety: "BRRI-28 Organic",
    quantityKg: 3500,
    minOrderKg: 40,
    pricePerKg: 34,
    govPrice: 35,
    histAvgPrice: 36,
    harvestDate: "2026-09-28",
    isOrganic: true,
    isQcApproved: true,
    qcInspectorNotes: "আর্দ্রতা ১৪% এর নিচে, চকচকে দানা, কোনো মিশ্রণ নেই। Grade A+ Certified.",
    images: [
      "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?auto=format&fit=crop&w=800&q=80"
    ],
    shelfLifeDays: 365,
    district: "Jamalpur",
    upazila: "Jamalpur Sadar",
    description: "ব্রম্ভপুত্র নদের অববাহিকায় প্রাকৃতিকভাবে উৎপাদিত সেরা মানের ব্রি-২৮ চিকন ধান। সরাসরি কৃষক থেকে চালকল ও হোলসেলারদের জন্য প্রস্তুত।"
  },
  {
    id: "prod-2",
    farmerId: "farmer-5",
    name: "Fresh Diamond Potato (Alu)",
    banglaName: "টাটকা ডায়মন্ড গোল আলু",
    category: "ALU",
    variety: "Diamond Grade-1",
    quantityKg: 8200,
    minOrderKg: 50,
    pricePerKg: 29,
    govPrice: 32,
    histAvgPrice: 33,
    harvestDate: "2026-10-01",
    isOrganic: true,
    isQcApproved: true,
    qcInspectorNotes: "দাগহীন, সুষম গোল আকৃতি, কোল্ড স্টোরেজ উপযোগী শুকনো চামড়া।",
    images: [
      "https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1590165482129-1b8b27698780?auto=format&fit=crop&w=800&q=80"
    ],
    shelfLifeDays: 90,
    district: "Jamalpur",
    upazila: "Jamalpur Sadar",
    description: "জামালপুর সদর শরীফপুরের সেরা ডায়মন্ড আলু। চিপস কোম্পানি এবং ঢাকা-চট্টগ্রামের পাইকারদের জন্য বিশেষ মূল্য।"
  },
  {
    id: "prod-3",
    farmerId: "farmer-2",
    name: "Melandaha Hot Red Chili (Shukna Morich)",
    banglaName: "মেলান্দহের দেশি ঝাল লাল শুকনা মরিচ",
    category: "MORICH",
    variety: "Melandaha Local Deshi",
    quantityKg: 850,
    minOrderKg: 10,
    pricePerKg: 280,
    govPrice: 310,
    histAvgPrice: 320,
    harvestDate: "2026-09-25",
    isOrganic: true,
    isQcApproved: true,
    qcInspectorNotes: "তীব্র ঝাঁঝালো সুবাস, রোদে শুকানো, শতভাগ প্রাকৃতিক রং।",
    images: [
      "https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&w=800&q=80"
    ],
    shelfLifeDays: 180,
    district: "Jamalpur",
    upazila: "Melandaha",
    description: "মেলান্দহের বিখ্যাত দেশি ঝাল মরিচ। রোদে প্রাকৃতিকভাবে শুকানো, কোনো রাসায়নিক রঙ বা প্রিজারভেটিভ নেই।"
  },
  {
    id: "prod-4",
    farmerId: "farmer-2",
    name: "Deshi Gol Begun (Eggplant)",
    banglaName: "টাটকা দেশি গোল বেগুন",
    category: "BEGUN",
    variety: "Jamalpur Tal Begun",
    quantityKg: 650,
    minOrderKg: 10,
    pricePerKg: 42,
    govPrice: 48,
    histAvgPrice: 50,
    harvestDate: "2026-10-02",
    isOrganic: true,
    isQcApproved: true,
    qcInspectorNotes: "আজ সকালে মাঠ থেকে তোলা। পোকা-মাকড়মুক্ত মসৃণ ত্বক।",
    images: [
      "https://images.unsplash.com/photo-1528825871115-3581a5387919?auto=format&fit=crop&w=800&q=80"
    ],
    shelfLifeDays: 5,
    district: "Jamalpur",
    upazila: "Melandaha",
    description: "আজ ভোরবেলায় খেত থেকে তোলা নরম রসালো তাল বেগুন। বেগুন ভাজা বা ভর্তার জন্য অতুলনীয়।"
  },
  {
    id: "prod-5",
    farmerId: "farmer-3",
    name: "Jamuna Char Green Pointed Gourd (Potol)",
    banglaName: "যমুনা চরের কচি সবুজ পটল",
    category: "POTOL",
    variety: "Char Deshi",
    quantityKg: 900,
    minOrderKg: 15,
    pricePerKg: 35,
    govPrice: 40,
    histAvgPrice: 42,
    harvestDate: "2026-10-02",
    isOrganic: true,
    isQcApproved: true,
    qcInspectorNotes: "সতেজ সবুজ, কচি বীজ, কোনো কীটনাশকের অবশিষ্টাংশ নেই।",
    images: [
      "https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?auto=format&fit=crop&w=800&q=80"
    ],
    shelfLifeDays: 6,
    district: "Jamalpur",
    upazila: "Islampur",
    description: "ইসলামপুরের যমুনার পলিচরে ফলানো মিষ্টি কচি পটল। সম্পূর্ণ প্রাকৃতিক কম্পোস্ট সার দিয়ে চাষকৃত।"
  },
  {
    id: "prod-6",
    farmerId: "farmer-8",
    name: "Live Rui & Katla Fish (Yamuna Harvest)",
    banglaName: "যমুনার জ্যান্ত রুই ও কাতল মাছ",
    category: "MACH",
    variety: "River Harvest 2-3kg",
    quantityKg: 420,
    minOrderKg: 5,
    pricePerKg: 380,
    govPrice: 420,
    histAvgPrice: 430,
    harvestDate: "2026-10-02",
    isOrganic: true,
    isQcApproved: true,
    qcInspectorNotes: "ফরমালিনমুক্ত জ্যান্ত মাছ, প্রাকৃতিক নদী ও ঘের থেকে আহরিত।",
    images: [
      "https://images.unsplash.com/photo-1534483509719-3feaee7c30da?auto=format&fit=crop&w=800&q=80"
    ],
    shelfLifeDays: 2,
    district: "Jamalpur",
    upazila: "Dewanganj",
    description: "দেওয়ানগঞ্জের নদী সংযুক্ত পরিচ্ছন্ন জলাশয়ে বড় হওয়া সুস্বাদু রুই ও কাতল মাছ। অক্সিজেন ব্যাগে লাইভ ডেলিভারি।"
  },
  {
    id: "prod-7",
    farmerId: "farmer-10",
    name: "Taherpuri Deshi Onion (Peyaj)",
    banglaName: "তাহেরপুরী দেশি লাল পেঁয়াজ",
    category: "PEYAJ",
    variety: "Taherpuri Deshi",
    quantityKg: 4100,
    minOrderKg: 40,
    pricePerKg: 78,
    govPrice: 85,
    histAvgPrice: 90,
    harvestDate: "2026-09-30",
    isOrganic: false,
    isQcApproved: true,
    qcInspectorNotes: "শক্ত শুকনো খোসা, ঝাঁঝালো গন্ধ, দীর্ঘ মেয়াদে সংরক্ষণযোগ্য।",
    images: [
      "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=800&q=80"
    ],
    shelfLifeDays: 120,
    district: "Jamalpur",
    upazila: "Melandaha",
    description: "দেশি তাহেরপুরী জাতের কড়া ঝাঁঝের পেঁয়াজ। সরাসরি মাঠ থেকে প্যাকেজিং করে ট্রাক লোডে ডেলিভারি।"
  },
  {
    id: "prod-8",
    farmerId: "farmer-9",
    name: "Hydroponic Greenhouse Broccoli & Capsicum",
    banglaName: "গ্রিনহাউস ব্রকলি ও রঙিন ক্যাপসিকাম",
    category: "SHOBJI",
    variety: "F1 Hybrid Premium",
    quantityKg: 350,
    minOrderKg: 5,
    pricePerKg: 120,
    govPrice: 150,
    histAvgPrice: 160,
    harvestDate: "2026-10-02",
    isOrganic: true,
    isQcApproved: true,
    qcInspectorNotes: "আন্তর্জাতিক সুপারশপ গ্রেড, নিখুঁত রং ও ক্রাঞ্চি টেক্সচার।",
    images: [
      "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80"
    ],
    shelfLifeDays: 10,
    district: "Jamalpur",
    upazila: "Jamalpur Sadar",
    description: "জামালপুর সদর তিতাপাল্লায় মালচিং ও গ্রিনহাউস ড্রিপ ইরিগেশনে উৎপাদিত এক্সক্লুসিভ ব্রকলি ও ক্যাপসিকাম।"
  }
];

export const SEED_AUCTIONS = [
  {
    id: "auc-1",
    title: "100 Mon Aman Dhan (BRRI-49/28) for North Bengal Rice Mill",
    buyerName: "Pran Agro Sourcing Div.",
    category: "DHAN",
    quantityKg: 4000,
    targetPrice: 33,
    district: "Jamalpur",
    deadline: "2026-10-08T18:00:00Z",
    status: "ACTIVE",
    bids: [
      { id: "bid-1", farmer: "Alhaj Mokbul Hossain", price: 32.5, qty: 4000, time: "১০ মিনিট আগে" },
      { id: "bid-2", farmer: "Nazrul Islam", price: 33.0, qty: 4000, time: "১ ঘণ্টা আগে" },
      { id: "bid-3", farmer: "Sirajul Islam Master", price: 32.8, qty: 3500, time: "৩ ঘণ্টা আগে" },
    ]
  },
  {
    id: "auc-2",
    title: "50 Mon Export Grade Diamond Potato for Chaldal.com",
    buyerName: "Chaldal Direct Sourcing",
    category: "ALU",
    quantityKg: 2000,
    targetPrice: 28,
    district: "Jamalpur",
    deadline: "2026-10-05T12:00:00Z",
    status: "ACTIVE",
    bids: [
      { id: "bid-4", farmer: "Shahidul Alam", price: 28.5, qty: 2000, time: "৫ মিনিট আগে" },
      { id: "bid-5", farmer: "Faruk Ahmed", price: 29.0, qty: 1500, time: "৩০ মিনিট আগে" }
    ]
  }
];
